In [49]:

import pandas as pd

sales_data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Laptop"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Electronics"],
    "Quantity": [2, 10, 5, 3, 1],
    "Unit_Price": [50000, 500, 1500, 12000, 50000]
}

df = pd.DataFrame(sales_data)

df

    Product     Category  Quantity  Unit_Price
0    Laptop  Electronics         2       50000
1     Mouse  Accessories        10         500
2  Keyboard  Accessories         5        1500
3   Monitor  Electronics         3       12000
4    Laptop  Electronics         1       50000

### Explore the dataset

In [10]:
# Display the first five rows
df.head()

    Product     Category  Quantity  Unit_Price
0    Laptop  Electronics         2       50000
1     Mouse  Accessories        10         500
2  Keyboard  Accessories         5        1500
3   Monitor  Electronics         3       12000
4    Laptop  Electronics         1       50000

In [11]:
# Check the number of rows and columns
df.shape

(5, 4)

In [12]:
# Check column names, data types, and non-null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Product     5 non-null      str
 1   Category    5 non-null      str
 2   Quantity    5 non-null      int64
 3   Unit_Price  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [13]:
# Get basic statistical information
df.describe()

        Quantity    Unit_Price
count   5.000000      5.000000
mean    4.200000  22800.000000
std     3.563706  25235.391814
min     1.000000    500.000000
25%     2.000000   1500.000000
50%     3.000000  12000.000000
75%     5.000000  50000.000000
max    10.000000  50000.000000

In [14]:
# Count missing values in each column
df.isnull().sum()

Product       0
Category      0
Quantity      0
Unit_Price    0
dtype: int64

### sales analysis

In [50]:
df["Total_Sales"] = df["Quantity"] * df["Unit_Price"]

df

    Product     Category  Quantity  Unit_Price  Total_Sales
0    Laptop  Electronics         2       50000       100000
1     Mouse  Accessories        10         500         5000
2  Keyboard  Accessories         5        1500         7500
3   Monitor  Electronics         3       12000        36000
4    Laptop  Electronics         1       50000        50000

In [16]:
total_revenue = df["Total_Sales"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 198500

In [17]:
df.isnull().sum()

Product        0
Category       0
Quantity       0
Unit_Price     0
Total_Sales    0
dtype: int64

In [ ]:
1. What is Pandas?

Interview-ready answer: Pandas is a Python library used to load, clean, manipulate, analyze, and organize structured data.




2. What is a DataFrame?

Interview-ready answer: A DataFrame is a two-dimensional tabular data structure with labeled rows and columns. 
Different columns can have different data types.




3. Difference between head() and info()

- df.head() displays the first 5 rows by default. You can change the number, e.g. df.head(3).
- df.info() provides a summary including column names, non-null counts, data types, and memory usage.



4. What does df.shape return?

Small correction: Use df.shape, not df.shape().

shape is an attribute, not a method. It returns a tuple in the format (rows, columns).

Example: (5, 4) means 5 rows and 4 columns.



5. How do you check missing values?

df.isnull().sum()



- isnull() identifies missing values.
- sum() counts them in each column.

In [19]:
# Verify the calculation
df["Total_Sales"] = df["Quantity"] * df["Unit_Price"]
print(df[["Product", "Total_Sales"]])
print("Total Revenue:", df["Total_Sales"].sum())

    Product  Total_Sales
0    Laptop       100000
1     Mouse         5000
2  Keyboard         7500
3   Monitor        36000
4    Laptop        50000
Total Revenue: 198500

In [20]:
# Confirm with Python
print(df["Total_Sales"].sum())

198500

### Filter data

In [ ]:
Write Pandas code to display only the rows where Category is "Electronics".

Hint: Use df[...] with a condition on df["Category"].

In [22]:
if df["Category"] == "Electronics":
    print(df["Category"])
# Error

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [23]:
df[df["Category"] == "Electronics"]

   Product     Category  Quantity  Unit_Price  Total_Sales
0   Laptop  Electronics         2       50000       100000
3  Monitor  Electronics         3       12000        36000
4   Laptop  Electronics         1       50000        50000

In [ ]:
Write code to display only products whose Total_Sales is greater than ₹40,000.

In [25]:
df[df["Total_Sales"] >40000]

  Product     Category  Quantity  Unit_Price  Total_Sales
0  Laptop  Electronics         2       50000       100000
4  Laptop  Electronics         1       50000        50000

In [ ]:
Now try sorting the entire DataFrame by Total_Sales from highest to lowest.

Hint: Use df.sort_values() and its ascending parameter.

In [27]:
df.sort_values("Total_Sales")

    Product     Category  Quantity  Unit_Price  Total_Sales
1     Mouse  Accessories        10         500         5000
2  Keyboard  Accessories         5        1500         7500
3   Monitor  Electronics         3       12000        36000
4    Laptop  Electronics         1       50000        50000
0    Laptop  Electronics         2       50000       100000

In [28]:
df.sort_values("Total_Sales",ascending= False)

    Product     Category  Quantity  Unit_Price  Total_Sales
0    Laptop  Electronics         2       50000       100000
4    Laptop  Electronics         1       50000        50000
3   Monitor  Electronics         3       12000        36000
2  Keyboard  Accessories         5        1500         7500
1     Mouse  Accessories        10         500         5000

In [ ]:
What is the total sales revenue for each product category?

For example, you should get one total for Electronics and one for Accessories.

Hint: Use groupby() on Category, then sum the Total_Sales column.

In [30]:
df.groupby("Category")
sum(df["Total_Sales"])

198500

In [33]:
df.groupby("Category")["Total_Sales"].sum()

'''
groupby("Category") — groups products into Electronics and Accessories.
["Total_Sales"] — selects the sales column.
.sum() — adds the sales within each category.
'''

'\ngroupby("Category") — groups products into Electronics and Accessories.\n["Total_Sales"] — selects the sales column.\n.sum() — adds the sales within each category.\n'

In [34]:
df.groupby("Category")["Total_Sales"].sum()

Category
Accessories     12500
Electronics    186000
Name: Total_Sales, dtype: int64

### Sales Data Analysis

In [36]:
# Calculate total revenue
print("Total Revenue:", df["Total_Sales"].sum())

Total Revenue: 198500

In [37]:
# Find the best-selling product by revenue
df.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)

Product
Laptop      150000
Monitor      36000
Keyboard      7500
Mouse         5000
Name: Total_Sales, dtype: int64

In [38]:
# Find the highest-revenue category
category_sales = df.groupby("Category")["Total_Sales"].sum()

print(category_sales.idxmax())
print(category_sales.max())

Electronics
186000

In [39]:
# Check for missing values
print(df.isnull().sum())

Product        0
Category       0
Quantity       0
Unit_Price     0
Total_Sales    0
dtype: int64

In [42]:
print(df.isnull().mean()) # Check average

Product        0.0
Category       0.0
Quantity       0.0
Unit_Price     0.0
Total_Sales    0.0
dtype: float64

In [45]:
# Dataframe and Series 
import pandas as pd

series = pd.Series([100, 200, 300])

df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Monitor"],
    "Sales": [100, 200, 300]
})
print(series)
print(df)

0    100
1    200
2    300
dtype: int64
   Product  Sales
0   Laptop    100
1    Mouse    200
2  Monitor    300

In [52]:
# Sort_values and sort_index
df.sort_values("Total_Sales", ascending=False)
df.sort_index(ascending=True)

    Product     Category  Quantity  Unit_Price  Total_Sales
0    Laptop  Electronics         2       50000       100000
1     Mouse  Accessories        10         500         5000
2  Keyboard  Accessories         5        1500         7500
3   Monitor  Electronics         3       12000        36000
4    Laptop  Electronics         1       50000        50000